spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/institute_management}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    com.institute.management: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN